spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoRestApi
    username: igor
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # create-drop / validate / update
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.example: DEBUG
  file:
    name: ./logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Формат виведення логів у консоль