spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoRestApi
    username: igor
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # ??? create-drop / validate / update, ???????? ??? ??????
    show-sql: true # ?????????? SQL-?????? ? ???????