spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoRestApi
    username: igor
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop #update
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.example: DEBUG
  file:
    name: ./logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
jwt:
  secret: Y2hglmdlbWVzc2FnZWFuZGVzY3JpcHQtY29tcGxleC1rZXk=
